add_newline = false
palette = "catppuccin_mocha"

#format = """[$directory](fg:lavender)($git_branch$git_state$git_status$git_metrics)$sudo$character"""
format = """$hostname$directory$sudo$character"""
right_format = """$all"""

[hostname]
ssh_only = true
format = '[$ssh_symbol](teal) on [$hostname](yellow bold) '
disabled = false

[directory]
style = "fg:lavender"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[git_branch]
format = "[\\[[$symbol$branch$tag](fg:blue)\\]](fg:sapphire)"
symbol = "\ue725 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)](fg:sky) '
cherry_pick = '[üçí PICKING](fg:teal)'

[git_status]
format = '([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]](fg:green)) '

[git_metrics]
format = '[+$added](fg:green)/[-$deleted](fg:yellow) '

[character]
success_symbol = '[¬ª](fg:green)'
error_symbol = '[‚úñ](fg:red)'

[nix_shell]
disabled = false
impure_msg = '[impure shell](fg:red)'
pure_msg = '[pure shell](fg:green)'
unknown_msg = '[unknown shell](fg:yellow)'
format = 'via [‚òÉÔ∏è $state( \($name\))](fg:blue) '

[ruby]
disabled = true

[swift]
disabled = true

[sudo]
format = '[as $symbol]($style) '
style = 'fg:peach'
symbol = 'üßô'
disabled = false

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
